spring:
  config:
    activate:
      on-profile: ci

  data:
    mongodb:
      uri: ${MONGODB_TEST_URI}

  main:
    lazy-initialization: true

app:
  jwt:
    secret-key: bd25ec392f76dbc79a278b5317d4fb0a796c780c04f49e4c0ac763419c518c5c
    refresh:
      secret-key: bd25ec392f76dbc79a278b531799fb0a796c780c04f49e4c0ac763419c518crd
  admin:
    init-login: admin
    init-password: admin123
  security:
    bcrypt-strength: 4

logging:
  level:
    root: WARN
    com.kyojin.packagito: INFO
    org.springframework.data.mongodb: ERROR
    org.springframework.security: ERROR