spring:
  config:
    activate:
      on-profile: ci

  data:
    mongodb:
      uri: ${MONGODB_TEST_URI}

  main:
    lazy-initialization: true

app:
  security:
    bcrypt-strength: 4

logging:
  level:
    root: WARN
    com.kyojin.packagito: INFO
    org.springframework.data.mongodb: ERROR
    org.springframework.security: ERROR