server:
  port: ${SPRING_PORT:8080}

spring:
  application:
    name: packagito
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  mvc:
    servlet:
      path: /api

springdoc:
  swagger-ui:
    path: /swagger.html

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG