server:
  port: ${SPRING_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}

spring:
  application:
    name: packagito
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs


app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-ms: ${JWT_EXPIRATION_MS:1200000}
    issuer: ${JWT_ISSUER_NAME:PackagitoApp}
    cookie-name: ${JWT_COOKIE_NAME:jwt-token}
    refresh:
      secret-key: ${JWT_REFRESH_SECRET_KEY}
      expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
      cookie-name: ${JWT_REFRESH_COOKIE_NAME:refresh_token}
  security:
    role-prefix: ${SECURITY_ROLE_PREFIX:ROLE_}
    bcrypt-strength: ${SECURITY_BCRYPT_STRENGTH:10}
  admin:
    init-login: ${ADMIN_INIT_LOGIN}
    init-password: ${ADMIN_INIT_PASSWORD}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}