server:
  port: ${SPRING_PORT:8080}

spring:
  application:
    name: packagito
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG